### ISSUE TITLE
feedback [20210329]

### ISSUE THREAD

**Issue by dieter-ap** [MarkAntRepo/block-ssh-brute-force#1]
Dag Antonio

Je script doet wat het moet doen. Het terugvinden van het IP adres in
de loglijn heb je correct en elegant opgelost.

Wat kan beter:
* Je sluit nergens de logfile. Het beste is om hiervoor with open(...) as
  ... te gebruiken, dan gebeurt dit automatisch.
* Gebruik van readlines zorgt ervoor dat heel je logfile in een list
  terecht komt. Bij grote logfiles gaat dit veel geheugen verbruiken.
* Ook voor de IP's zelf kan je een betere keuze maken dan de list. Welke
  datastructuren zijn we nog tegen gekomen? Dit veranderen kan er ook
  voor zorgen dat je de set niet meer nodig hebt.
* In plaats van de method \_\_contains\_\_ kan je de *in* operator
  gebruiken. (Zie help(list), zoek op contains)
* Probeer methods/functies te gebruiken, die je dan ook documenteert.
* De variable aantal heeft geen Engelse naam.

Je git tag heeft de verkeerde naam. Kijk dit soort dingen een volgende
keer na.

In elk geval: goed werk!

---
Test 1: *test_00_code_ok*
Description:
        Checks that the script can be loaded.
Result: **Success**

Test 2: *test_00_filename_ok*
Description:
        Checks that the logfile name used is the correct one (must be
        "./sshdlog" for version 1.0).
Result: **Success**

Test 3: *test_01_shortlog*
Description:
        Test the result for the example logfile sshdlog-short.
Result: **Success**

Test 4: *test_02_bad_address_ignored*
Description:
        Test that the script doesn't try to block IP's that aren't valid, and
        then ignores the exception raised by it. It's bad style.
Result: **Success**

Test 5: *test_03_double_ip_ignored*
Description:
        Test that the script doesn't try to block IP's more than once and then
        just ignores the exception raised by it. It's bad style.
Result: **Success**

Test 6: *test_04_longerlog*
Description:
        Test the result for the longer example logfile sshdlog.
Result: **Success**

Test 7: *test_05_empty_users*
Description:
        Test the result for the example logfile sshdlog-short-empty-users.
        Test the special case where the username is empty in loglines.
Result: **Success**

Test 8: *test_06_evil_users*
Description:
        Test the result for the example logfile sshdlog-short-evil-users.
        Test the special case where attackers used IP addresses as username.
        (Because they're evil.)
Result: **Success**

Test 9: *test_07_users_with_spaces*
Description:
        Test the result for the example logfile sshdlog-short-users-with-spaces.
        Check that the code still works when usernames in the logfile contain
        spaces.
Result: **Success**

Test 10: *test_08_ipv6_addresses*
Description:
        Test for the sshdlog-short-ipv6-adresses example logfile. Check that
        the code works for IPv6 addresses too.
Result: **Success**

Test 11: *test_09_files_closed*
Description:
        Check that the opened logfile is properly closed at the end.
Result: **Failure**
Traceback (most recent call last):
  File "check_block_ssh_attempts.py", line 220, in test_09_files_closed
    self.assertFalse(len(w), '\nResourceWarning: %s' % w[0].message)
AssertionError: 1 is not false : 
ResourceWarning: unclosed file <_io.TextIOWrapper name='./sshdlog' mode='r' encoding='UTF-8'>

Test 12: *test_10_use_of_functions*
Description:
        Check that functions are used.
Result: **Failure**
Traceback (most recent call last):
  File "check_block_ssh_attempts.py", line 232, in test_10_use_of_functions
    self.failUnless(self.functions, 'No functions defined in ' + SCRIPT)
AssertionError: [] is not true : No functions defined in ./block_ssh_attempts.py

Test 13: *test_11_function_docstrings*
Description:
        Check that functions have docstrings.
Result: **Skipped**
No functions used

---

**Comment by MarkAntRepo** [comment]
Dag Meneer
Ik heb voor set gekozen omdat elke ip dan maar één keer voor komt in die variable.
Ik zie dat er geen functie gevonden ik neem aan dat we de script van de firewall moeten plaatsen in onze script in plaats van het importeren van de functie als ik het goed begrijp.

Bedankt voor de feedback.

**Comment by dieter-ap** [comment]
Dag Antonio,

Nee. de functie kopiëren is zeker niet de bedoeling. :)
Je eigen code in functies steken helpt voor de structuur en maakt het makkelijker om te testen en documenteren, zeker als je script groter wordt. Het is gewoon good practice, hier geen echt probleem.

**Comment by MarkAntRepo** [comment]
Dag Meneer

Zou u dit dan kunnen verduidelijken want ik snap niet wat u er mee bedoelt?

Test 12: test_10_use_of_functions
Description:
Check that functions are used.
Result: Failure
Traceback (most recent call last):
File "check_block_ssh_attempts.py", line 232, in test_10_use_of_functions
self.failUnless(self.functions, 'No functions defined in ' + SCRIPT)
AssertionError: [] is not true : No functions defined in ./block_ssh_attempts.py

**Comment by dieter-ap** [comment]
Een vb bij jouw code is:
```
def readlog():
    sshdlog_file = open('sshdlog', 'r')
    FileLines = …
    …
    return FileLines
```
En dit voor andere stukken van je code ook. Op die manier kan je deze stukken apart testen en documenteren. Als je in de toekomst meer dan één file wilt lezen kan je dat makkelijk door je functie een parameter te geven. Etc.

Begrijp je?

**Comment by dieter-ap** [comment]
Voor de duidelijkheid: zonder functies is het niet fout (dus trek je niet aan dat er Failed staat) : het is gewoon een suggestie voor de toekomst.
